apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskprocessor:2.0
spec:
  selector:
    matchLabels:
      app: taskprocessor:2.0
  template:
    metadata:
      labels:
        app: taskprocessor:2.0
        db: in-memory
    spec:
      containers:
      - name: taskprocessor:2.0
        image: lauxy1/taskprocessor:2.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            cpu: "200m"
            memory: "64Mi"  
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"  
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: user
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: password   
        ports:
          - containerPort: 80
 
---
apiVersion: v1
kind: Service
metadata:
  name: taskprocessor:2.0
spec:
  type: NodePort
  selector:
    app: taskprocessor:2.0
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: taskprocessor:2.0
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: taskprocessor:2.0
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 85